### ISSUE TITLE
How to set VSS_NUGET_EXTERNAL_FEED_ENDPOINTS in Azure pipeline?

### ISSUE THREAD

**Issue by PeterJakubik** [Microsoft/artifacts-credprovider#43]
Hello
I'm not sure if this belongs to this repository.
I set up an Azure DevOps Pipeline and tried to get nugets from telerik feed with auth, but this doesn't work with credential provider (as described here [https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/dotnet-exe](url))
My Pipeline:
```yaml
steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.8.1'
  inputs:
    versionSpec: 4.8.1
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'
    feedsToUse: config
    nugetConfigPath: src/SomeObscureWeb/NuGet.Config
```
I tried specifying json in VSS_NUGET_EXTERNAL_FEED_ENDPOINTS as Pipeline Variable but it doesn't seem that credential provider in pipline is using this value.

My VSS_NUGET_EXTERNAL_FEED_ENDPOINTS looks like this
```javascript
{"endpointCredentials": [{
"endpoint":"https://nuget.telerik.com/nuget", 
"username":"user@host.com", 
"password":"xxx"}]}
```

How should I setup VSS_NUGET_EXTERNAL_FEED_ENDPOINTS for Azure Pipline to add new feed with credentials? 

Thank you
Peter
