### ISSUE TITLE
[YAML-BUILD] 401 when building Dockerfile in Build Agent (Interactive?)

### ISSUE THREAD

**Issue by kieronlanning** [Microsoft/artifacts-credprovider#73]
Passing in the `$(System.AccessToken)` and using a custom NuGet.config, I'm seeing this error in the build:

*Error*
```
/usr/share/dotnet/sdk/2.2.104/NuGet.targets(114,5): warning : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet` [/src/Solution/Project.csproj]
/usr/share/dotnet/sdk/2.2.104/NuGet.targets(114,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/1234567890/_packaging/0987654321/nuget/v3/index.json. [/src/Solution/Project.csproj]
/usr/share/dotnet/sdk/2.2.104/NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/src/Solution/Project.csproj]
```

*Build YAML*
```
variables:
  PAT: $(System.AccessToken)
...

- task: DockerCompose@0
  displayName: Container build
  inputs:
    action: Build services
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: $(projectRootPath)/docker-compose.yml
    additionalDockerComposeFiles: docker-compose.az-build.yml
  env:
    DOCKER_REGISTRY: $(azureContainerRegistry)/
    PAT: $(PAT)
```

*Dockerfile*

```
FROM microsoft/dotnet:2.2-sdk AS sdk-base

ARG FEED_URL
ARG PAT

FROM microsoft/dotnet:2.2-aspnetcore-runtime-alpine AS runtime-base

FROM sdk-base AS build

ARG FEED_URL
ARG PAT

# Install the Credential Provider to configure the access
RUN wget -qO- https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh | bash

# Configure the environment variables
ENV NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED true
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS "{\"endpointCredentials\": [{\"endpoint\":\"${FEED_URL}\", \"password\":\"${PAT}\"}]}"

WORKDIR /src
COPY ["Solution/Project.csproj", "Solution/"]
COPY ["NuGet.config", "."]

RUN dotnet restore "Solution/Project.csproj" --configfile ./NuGet.config -v quiet
```

*NuGet.config*

```
<configuration>
  <packageSources>
    <clear />
    <add key="0987654321" value="https://pkgs.dev.azure.com/1234567890/_packaging/0987654321/nuget/v3/index.json." protocolVersion="3" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
</configuration>
```
